# Generated by Django 6.0 on 2025-12-16 08:50

import django.db.models.deletion
import sitemanagement.constants.image_save_path
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vin_code', models.CharField(max_length=17, verbose_name='VIN код автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('image', models.ImageField(upload_to=sitemanagement.constants.image_save_path.qr_upload_path, verbose_name='Фото QR кода')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('deactivated', 'Деактивирован по таймеру')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_printed', models.BooleanField(default=False, verbose_name='Статус распечатки')),
                ('is_printed_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата распечатки')),
                ('is_deployed', models.BooleanField(default=False, verbose_name='Отгружено партнеру')),
                ('is_deployed_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата отгрузки')),
                ('is_selled', models.BooleanField(default=False, verbose_name='Статус реализации партнером')),
                ('is_active', models.BooleanField(default=False, verbose_name='Статус активации клиентом')),
                ('is_selled_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации')),
                ('active_before', models.DateTimeField(blank=True, null=True, verbose_name='Таймер деактивации')),
                ('Car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitemanagement.car', verbose_name='Автомобиль клиента')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'QR код',
                'verbose_name_plural': 'QR коды',
            },
        ),
    ]
