# Generated by Django 6.0 on 2025-12-16 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Название компании партнера')),
                ('partner_prefix', models.CharField(max_length=2, verbose_name='Префикс для QR кода')),
            ],
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата активации'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='selled_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_qrcodes', to=settings.AUTH_USER_MODEL, verbose_name='Продано менеджером'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='is_deployed_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='is_printed_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата распечатки'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='is_selled_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата реализации'),
        ),
    ]
