# Generated by Django 6.0 on 2025-12-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0002_partners_qrcode_is_active_timestamp_qrcode_selled_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partners',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterField(
            model_name='partners',
            name='partner_prefix',
            field=models.CharField(blank=True, editable=False, max_length=2, verbose_name='Префикс для QR кода'),
        ),
    ]
