# Generated by Django 6.0 on 2025-12-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0003_alter_partners_options_alter_partners_partner_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='account_type',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('P', 'Premium')], default='L', max_length=1),
        ),
    ]
