# Generated by Django 6.0 on 2025-12-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0004_qrcode_account_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partners',
            new_name='Partner',
        ),
        migrations.RenameField(
            model_name='qrcode',
            old_name='Car',
            new_name='сar',
        ),
        migrations.AddField(
            model_name='qrcode',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sitemanagement.partner', verbose_name='Автомобиль клиента'),
        ),
    ]
