# Generated by Django 6.0 on 2025-12-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0005_rename_partners_partner_rename_car_qrcode_сar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='сar',
            new_name='car',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitemanagement.partner', verbose_name='Партнер'),
        ),
    ]
