# Generated by Django 6.0 on 2025-12-16 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0006_rename_сar_qrcode_car_alter_qrcode_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='account_type',
            field=models.CharField(choices=[('L', 'Light'), ('M', 'Medium'), ('P', 'Premium')], default='L', help_text='Тип тарифного плана (L/M/P) - влияет на генерацию кода', max_length=1, verbose_name='Тарифный план'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='code',
            field=models.CharField(max_length=255, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='partner',
            field=models.ForeignKey(help_text='Выберите партнера для использования префикса в QR коде', on_delete=django.db.models.deletion.PROTECT, to='sitemanagement.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('deactivated', 'Деактивирован по таймеру')], default='active', max_length=15, verbose_name='Статус активности'),
        ),
    ]
