# Generated by Django 6.0 on 2025-12-16 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0007_alter_qrcode_account_type_alter_qrcode_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='partner',
            field=models.ForeignKey(help_text='Партнер для использования префикса в QR коде', on_delete=django.db.models.deletion.PROTECT, to='sitemanagement.partner', verbose_name='Партнер'),
        ),
    ]
