# Generated by Django 6.0 on 2025-12-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0008_alter_qrcode_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название свойства')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('premium', 'Premium')], max_length=10, verbose_name='Название тарифного плана')),
                ('price', models.IntegerField(verbose_name='Стоимость тарифного плана / месяц')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемость')),
                ('features', models.ManyToManyField(related_name='membership_plans', to='sitemanagement.feature', verbose_name='Свойства')),
            ],
            options={
                'verbose_name': 'Тарифный план',
                'verbose_name_plural': 'Тарифные планы',
                'ordering': ['id'],
            },
        ),
    ]
