# Generated by Django 6.0 on 2025-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0009_feature_alter_car_options_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стоимость тарифного плана / месяц'),
        ),
    ]
