# Generated by Django 6.0 on 2025-12-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0011_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17)),
            ],
            options={
                'verbose_name': 'Лид на главной',
                'verbose_name_plural': 'Лиды на главной',
            },
        ),
    ]
