# Generated by Django 6.0.1 on 2026-01-23 14:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_alter_bodytype_options'),
        ('sitemanagement', '0013_car_user'),
    ]

    operations = [
    migrations.AddField(
        model_name='car',
        name='body_type',
        field=models.ForeignKey(
            default=1, 
            on_delete=django.db.models.deletion.PROTECT,
            to='dictionaries.bodytype',
            verbose_name='Кузов автомобиля клиента'
        ),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='car',
        name='brand',
        field=models.ForeignKey(
            default=1, 
            on_delete=django.db.models.deletion.PROTECT,
            to='dictionaries.brand',
            verbose_name='Марка автомобиля клиента'
        ),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='car',
        name='color',
        field=models.ForeignKey(
            default=1,
            on_delete=django.db.models.deletion.PROTECT,
            to='dictionaries.colors',
            verbose_name='Цвет автомобиля клиента'
        ),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='car',
        name='lising_company',
        field=models.ForeignKey(
            default=3,  
            on_delete=django.db.models.deletion.PROTECT,
            to='sitemanagement.partner',
            verbose_name='Лизинговая компания'
        ),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='car',
        name='model',
        field=models.ForeignKey(
            default=1, 
            on_delete=django.db.models.deletion.PROTECT,
            to='dictionaries.model',
            verbose_name='Модель автомобиля клиента'
        ),
        preserve_default=False,
    ),
    migrations.AddField(
        model_name='car',
        name='year_built',
        field=models.PositiveIntegerField(
            default=2024,
            validators=[
                django.core.validators.MinValueValidator(1980),
                django.core.validators.MaxValueValidator(2026)
            ],
            verbose_name='Год выпуска'
        ),
        preserve_default=False,
    ),
]
