# Generated by Django 6.0.1 on 2026-01-23 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0014_car_body_type_car_brand_car_color_car_lising_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='qr_code',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_instance', to='sitemanagement.qrcode', verbose_name='QR код автомобиля'),
        ),
    ]
