# Generated by Django 6.0.1 on 2026-01-23 21:31

import sitemanagement.constants.image_save_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0015_remove_qrcode_car_car_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=sitemanagement.constants.image_save_path.car_image_upload_path, verbose_name='Фото пользователя'),
        ),
    ]
