# Generated by Django 6.0.1 on 2026-01-23 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0016_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='licence_plate',
            field=models.CharField(default=1, max_length=15, verbose_name='Номерной знак авто'), # type: ignore
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='qr_code',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='car_instance', to='sitemanagement.qrcode', verbose_name='QR код автомобиля'),
            preserve_default=False,
        ),
    ]
