# Generated by Django 6.0.1 on 2026-01-27 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0018_alter_car_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tranasctions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('auto_renewal', models.BooleanField(default=False, verbose_name='Автоматическое продление')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('completed', 'Выполнено'), ('failed', 'Не выполнено')], max_length=10, verbose_name='Статус')),
                ('request_id', models.CharField(max_length=255, verbose_name='Request ID в bePaid')),
                ('bepaid_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID транзакции в bePaid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('subscription_start', models.DateTimeField(blank=True, null=True, verbose_name='Начало подписки')),
                ('subscription_end', models.DateTimeField(blank=True, null=True, verbose_name='Окончание подписки')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitemanagement.membership', verbose_name='Тарифный план')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-id'],
            },
        ),
    ]
