# Generated by Django 6.0.1 on 2026-01-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0019_tranasctions'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='redirect_url',
            field=models.CharField(default='https://example.com', max_length=255),
            preserve_default=False,
        ),
    ]
