# Generated by Django 6.0.1 on 2026-01-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0020_partner_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
