# Generated by Django 6.0.1 on 2026-01-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0021_qrcode_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='Статус использования'),
        ),
    ]
