# Generated by Django 6.0.1 on 2026-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0022_alter_qrcode_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text="Если выставлено True, то клиент 'удалил' машину", verbose_name='Статус удаления'),
        ),
    ]
