# Generated by Django 6.0.1 on 2026-02-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0023_car_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='active_before',
            field=models.DateTimeField(blank=True, help_text='Если пользователь не активировал QR код за 60 дней, то он будет деактивирован', null=True, verbose_name='Время деактивации'),
        ),
    ]
