# Generated by Django 6.0.2 on 2026-02-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0024_alter_qrcode_active_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.CharField(choices=[('free', 'Нет подписки'), ('light', 'Light'), ('medium', 'Medium'), ('premium', 'Premium')], max_length=10, verbose_name='Название тарифного плана'),
        ),
    ]
