# Generated by Django 6.0.2 on 2026-02-11 17:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0025_alter_membership_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tranasctions',
            new_name='Transactions',
        ),
    ]
