# Generated by Django 6.0.2 on 2026-02-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0026_rename_tranasctions_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='plan',
            field=models.CharField(choices=[('free', 'Нет подписки'), ('light', 'Стартовый'), ('medium', 'Оптимальный'), ('premium', 'Премиум')], max_length=10, verbose_name='Название тарифного плана'),
        ),
    ]
