# Generated by Django 6.0.2 on 2026-02-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanagement', '0027_alter_membership_plan'),
    ]

    operations = [
    ]
