# Generated by Django 6.0 on 2025-12-23 14:55

import django.db.models.deletion
import sitemanagement.constants.image_save_path
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('phone_number', models.CharField(max_length=18, unique=True, verbose_name='Номер телефона')),
                ('account_type', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('premium', 'Premium')], max_length=20, verbose_name='Тип аккаунта')),
                ('privacy_accepted', models.BooleanField(default=False, verbose_name='Принятие политики конфиденциальности')),
                ('image', models.ImageField(blank=True, null=True, upload_to=sitemanagement.constants.image_save_path.user_image_upload_path, verbose_name='Фото пользователя')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
