# Generated by Django 6.0.1 on 2026-01-22 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userprofile_options_userprofile_user_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('premium', 'Premium'), ('headOfficeManager', 'Head Office Manager'), ('headServiceCenterDepartment', 'Head Service Center Department'), ('specialist', 'Specialist')], max_length=50, verbose_name='Тип аккаунта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
