# Generated by Django 6.0.1 on 2026-01-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userprofile_account_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='account_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='client_account_type',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('medium', 'Medium'), ('premium', 'Premium')], max_length=20, null=True, verbose_name='Тип аккаунта (для клиентов)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manager_account_type',
            field=models.CharField(blank=True, choices=[('headOfficeManager', 'Head Office Manager'), ('headServiceCenterDepartment', 'Head Service Center Department'), ('specialist', 'Specialist')], max_length=50, null=True, verbose_name='Тип аккаунта (для менеджеров)'),
        ),
    ]
