# Generated by Django 6.0.1 on 2026-01-22 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_userprofile_account_type_and_more'),
        ('sitemanagement', '0013_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Компания, в которой работает менеджер', null=True, on_delete=django.db.models.deletion.PROTECT, to='sitemanagement.partner', verbose_name='Партнер'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='manager_account_type',
            field=models.CharField(blank=True, choices=[('headOfficeManager', 'Руководитель ГО'), ('headServiceCenterDepartment', 'Начальник отдела ЦУ'), ('specialist', 'Специалист ЦУ')], max_length=50, null=True, verbose_name='Тип аккаунта (для менеджеров)'),
        ),
    ]
