# Generated by Django 6.0.1 on 2026-01-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_address_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram ID клиента'),
        ),
    ]
