# Generated by Django 6.0.1 on 2026-01-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел'),
        ),
    ]
