# Generated by Django 6.0.2 on 2026-02-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='manager_account_type',
            field=models.CharField(blank=True, choices=[('supervisor', 'Руководитель'), ('manager', 'Менеджер')], max_length=50, null=True, verbose_name='Тип аккаунта (для менеджеров)'),
        ),
    ]
