# Generated by Django 6.0.2 on 2026-02-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userprofile_manager_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='client_account_type',
            field=models.CharField(blank=True, choices=[('free', 'Нет подписки'), ('light', 'Light'), ('medium', 'Medium'), ('premium', 'Premium')], max_length=20, null=True, verbose_name='Тип аккаунта (для клиентов)'),
        ),
    ]
