servers:
  hosts:
    autoconcierge:
      ansible_host: ids-help.by

  vars:
    ansible_user: root

    app: prod

    user: ids
    timezone: Europe/Minsk
    ssh_keys: |
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP+igmEmZ9KzELTgYKLrW/LcFIclzj0m2enPp5Bm4QSz promo@vhome6
      ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFIOJE+HAkS+l7kDMNsQAMsVxdBoKn6UKg1NwO/KJ5I+ timofey.syr17@gmail.com

    docker_tag: prod
    docker_network_prefix: "172.56.10"

    db_admin_user: admin
    db_admin_password: yei8chaShahJ6eijal0o
    db_admin_name: admin

    db_user: ids
    db_password: caThahcheijihoh4Eela
    db_name: autoconcierge

    registry_user: gitlab+deploy-token-10438306
    registry_token: gldt-FY7JGssBzRdxNXVfthRn

    domain: ids-help.by
    enable_https: true

    http_user: autoconcierge
    http_pass: welcome
    http_auth: false
