import type { Metadata } from 'next'
import './globals.css'
import { Providers } from './providers/Providers'
import { Toaster } from 'react-hot-toast'
import Header from '@/components/Header'
import Footer from '@/components/Footer'

export const metadata: Metadata = {
  title: 'СБЛ-Лизинг',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className="font-display flex min-h-screen flex-col"> 
        <Providers>
          <Header />
          <Toaster />
          <main className="grow">{children}</main> 
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
