services:
  backend:
    image: "registry.gitlab.com/wedeving/autoconcierge-www/backend:{{ docker_tag }}"
    volumes:
      - "static:/static"
      - "media:/media"
    environment:
      # django settings
      ALLOWED_HOSTS: "{{domain}},backend"
      SECRET_KEY: "django-insecure-=a^u2d6yc22l-&*#h04x*ek6si5i8%%uxe($a9uat5v0(np&e%"
      DEBUG_MODE: false
      BASE_URL: "https://{{ domain }}"
      MEDIA_ROOT: /media
      STATIC_ROOT: /static
      CORS_ALLOW_ALL_ORIGINS: false
      CORS_ALLOWED_ORIGINS: "http://{{ domain }},https://{{ domain }},http://{{ domain_manager }},https://{{ domain_manager }}"
      CSRF_TRUSTED_ORIGINS: "http://{{ domain }},https://{{ domain }},http://{{ domain_manager }},https://{{ domain_manager }}"

      # database
      DB_NAME: "{{ db_name }}"
      DB_USER: "{{ db_user }}"
      DB_PASSWORD: "{{ db_password }}"
      DB_HOST: postgres
      DB_PORT: 5432

      # redis
      REDIS_HOST: redis

      #sms service
      SMS_USER: info@zoopolis.org
      SMS_API_KEY: SPsIpFIV9UGwaPXuZuT7

      # activation url
      ACTIVATION_URL: "https://manager.{{ domain }}/activation"

    healthcheck:
      test: ["CMD", "sh", "-c", "ss -nltp | grep '0.0.0.0:8000'"]
      interval: 2s
      timeout: 1s
      retries: 40
      start_period: 1s

    networks:
      autoconcierge:
        ipv4_address: "{{ docker_network_prefix }}.10"

    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy

  frontend:
    image: "registry.gitlab.com/wedeving/autoconcierge-www/frontend:{{ docker_tag }}"
    environment:
      NEXT_PUBLIC_API_URL: https://{{ domain }}/api/v1
      BACKEND_URL: http://backend:8000/api/v1
      NEXTAUTH_URL: https://{{ domain }}
      NEXTAUTH_SECRET: sdjfhshd126kbnaoTj12
      CHECKOUT_URL: https://checkout.bepaid.by/ctp/api/checkouts
      PAYMENTS_TEST_MODE: true
      BEPAID_ID: 33998
      BEPAID_SECRET_KEY: b9c8a46a85d78a885ef10efdf50a959fc6b3872233958b7ccc5630254aca4b8c
      BEPAID_PRIVATE_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvIkf0fiX6xsaWCCg0pasik2UkNZtQCFEeoY1lZJesUQoUWRbV/3iYVUXGws01LotyfmcKD/OaTusgHssiXcLbSVlCC1YTEX2TXgUZxO5BfzCLSWPqgz37lQw2e3/a14Q1t6/B7dF6DX21iw2A54iXt1lKXWZ/CjOdlKqDQrT5TcGNWLIqnzgorbDSvwXH0dKCQKK23lGB8IIIx+V4zVtZhgqtvgW6D4Z07ahVUXTn/dc590UwltWkkskSgMczQb/ZAG1eDS/VuhlrcfobTt4e2VO3I167J5i+IKdwXzzWT5sq97u5QAGCuQzeJF1t87OVQKDZDjbtk/DgQWBG+AKnwIDAQAB

    networks:
      autoconcierge:
        ipv4_address: "{{ docker_network_prefix }}.11"
    depends_on:
      backend:
        condition: service_healthy

  manager-frontend:
    image: "registry.gitlab.com/wedeving/autoconcierge-www/manager-frontend:{{ docker_tag }}"
    environment:
      NEXT_PUBLIC_API_URL: https://{{ domain }}/api/v1
      BACKEND_URL: http://backend:8000/api/v1
      NEXTAUTH_URL: https://{{ domain_manager }}
      NEXTAUTH_SECRET: ajsdfg-jbdf-12

    networks:
      autoconcierge:
        ipv4_address: "{{ docker_network_prefix }}.12"
    depends_on:
      backend:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    volumes:
      - "postgres:/var/lib/postgresql/18/docker"
    environment:
      - POSTGRES_USER={{ db_admin_user }}
      - POSTGRES_PASSWORD={{ db_admin_password }}
      - POSTGRES_DB={{ db_admin_name }}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      autoconcierge:
        ipv4_address: "{{ docker_network_prefix }}.20"

  redis:
    image: redis:8-alpine
    volumes:
      - "redis:/data"
    networks:
      autoconcierge:
        ipv4_address: "{{ docker_network_prefix }}.21"

networks:
  autoconcierge:
    name: "{{ app }}_network"
    ipam:
      config:
        - subnet: "{{ docker_network_prefix }}.0/24"

volumes:
  media:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/{{ app }}/media"
  static:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/{{ app }}/static"
  redis:
  postgres:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "/var/{{ app }}/postgres"
