# Generated by Django 6.0.1 on 2026-01-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytype',
            options={'verbose_name': 'Кузов автомобиля', 'verbose_name_plural': 'Кузова автомобилей'},
        ),
    ]
