# Generated by Django 6.0.2 on 2026-02-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_alter_bodytype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='name',
            field=models.CharField(help_text='например: 5-series', max_length=255, verbose_name='Название модели'),
        ),
    ]
