- name: Base
  hosts: servers
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - curl
          - rsync
          - git
          - htop
          - sudo
          - tmux
          - vim
          - gpg
          - gnupg
          - ca-certificates
          - starship
          - fish
          - prometheus-node-exporter
        state: present
    - name: Timezone
      community.general.timezone:
        name: "{{ timezone }}"
    - name: Hostname
      ansible.builtin.hostname:
        name: "{{ domain }}"
    - name: Create user
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /usr/bin/fish
        groups: sudo
        append: true
    - name: Sudo config
      ansible.builtin.copy:
        dest: /etc/sudoers.d/sudo_no_pass
        mode: "0644"
        content: |
          %sudo ALL=(ALL:ALL) NOPASSWD:ALL
    - name: Ssh dir
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        mode: "0755"
    - name: Ssh dir
      ansible.builtin.file:
        path: "/home/{{ user }}/.ssh"
        state: directory
        mode: "0755"
    - name: Ssh keys
      ansible.builtin.copy:
        dest: "/home/{{ user }}/.ssh/authorized_keys"
        content: "{{ ssh_keys }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0600"

    - name: Configure prometheus node exporter
      ansible.builtin.copy:
        dest: /etc/default/prometheus-node-exporter
        content: 'ARGS="--web.listen-address=127.0.0.1:9100"'
        mode: "0644"
      notify: Restart prometheus-node-exporter

    - name: Configure starship
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.config/fish/config.fish"
        line: "starship init fish | source"
        create: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: "0644"

  handlers:
    - name: Restart prometheus-node-exporter
      ansible.builtin.service:
        name: prometheus-node-exporter
        state: restarted
